[blog]
image="ghcr.io/ublue-os/arch-toolbox:latest"
home="$HOME/.distrobox/homes/blog"
pre_init_hooks=echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen && pacman -Syu --noconfirm
#pre_init_hooks=chown -R derek:derek ${HOME}/.distrobox/homes/blog/
additional_packages="base base-devel wget curl bash-completion bc chezmoi fzf fd git glibc neovim"
additional_packages="npm nodejs ripgrep rsync ruby ruby-bundler ruby-erb jekyll tree"
additional_packages="tree-sitter"
init_hooks=chezmoi init --apply --no-tty --force https://github.com/derekbarbosa/dotfiles-chezmoi.git --branch blogdev
init_hooks=nvim -f --headless -c ":Lazy install" +MasonToolsInstallSync +qall
init_hooks=chmod -R ugo+rw ${HOME}/
init_hooks=chown -R derek:derek ${HOME}/
pull=true
replace=true
